### PR TITLE
filing cabinet

### PR DESCRIPTION
**Pull request by cadenceblorbo**
adds filing cabinet obstacle
adds local space workflow for timer platform (useful for prefabs)

### CODE REVIEW

**Review by jidaprano — COMMENTED** [review]
Movement and timing is good; any chance you could put a triangle timer on the side of the filing cabinet instead of/in addition to the one on the front? If I'm jumping on the cabinet from the side, I can't really see the countdown timer at all currently.

**Comment by cadenceblorbo** [comment]
I can look into it!

> Movement and timing is good; any chance you could put a triangle timer on the side of the filing cabinet instead of/in addition to the one on the front? If I'm jumping on the cabinet from the side, I can't really see the countdown timer at all currently.

**Comment by cadenceblorbo** [comment]
> Movement and timing is good; any chance you could put a triangle timer on the side of the filing cabinet instead of/in addition to the one on the front? If I'm jumping on the cabinet from the side, I can't really see the countdown timer at all currently.

done! added it to top of platform incase user is looking straight down

**Comment by cadenceblorbo** [comment]
indicator changes approved by saran + paige

**Pull request merged**
